# Generated by Django 5.2.16 on 2026-07-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('code_postal', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('commission_gestion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_gestion_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valorisation_heure_proprietaire', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('poids_quote_part_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('poids_investissement_financier_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_investissement_temporel_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bien',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('contact_nom', models.CharField(blank=True, default='', max_length=150)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('specialite', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'entreprise',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'proprietaire',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('airbnb_ical_url', models.URLField(blank=True, default='', max_length=500)),
                ('dernier_sync_at', models.DateTimeField(blank=True, null=True)),
                ('dernier_sync_erreur', models.TextField(blank=True, default='')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='api.bien')),
            ],
            options={
                'db_table': 'appartement',
                'ordering': ['bien__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PartProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_part_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.bien')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.proprietaire')),
            ],
            options={
                'db_table': 'part_proprietaire',
                'ordering': ['bien', '-quote_part_pct'],
                'constraints': [models.UniqueConstraint(fields=('bien', 'proprietaire'), name='unique_part_par_bien_proprietaire')],
            },
        ),
    ]
