# Generated by Django 5.2.16 on 2026-07-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('airbnb', 'Airbnb'), ('direct', 'Direct'), ('autre', 'Autre')], default='airbnb', max_length=10)),
                ('uid_externe', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('libelle', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='confirmee', max_length=10)),
                ('montant_revenu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.appartement')),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('uid_externe', ''), _negated=True), fields=('appartement', 'uid_externe'), name='unique_reservation_par_uid_externe')],
            },
        ),
    ]
