# Generated by Django 5.2.16 on 2026-07-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('duree_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=10)),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appartement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='api.appartement')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='api.bien')),
                ('entreprise_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api.entreprise')),
                ('proprietaire_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches', to='api.proprietaire')),
            ],
            options={
                'db_table': 'tache',
                'ordering': ['-date_prevue', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payeur', models.CharField(choices=[('maison', 'Maison'), ('proprietaire', 'Propriétaire')], default='maison', max_length=15)),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures/%Y/%m/')),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietaire_payeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_avances', to='api.proprietaire')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='api.tache')),
            ],
            options={
                'db_table': 'frais',
                'ordering': ['-created_at'],
            },
        ),
    ]
