# Generated by Django 5.2.16 on 2026-07-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tache_frais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApportInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apports', to='api.bien')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apports', to='api.proprietaire')),
            ],
            options={
                'db_table': 'apport_initial',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField()),
                ('moyen_paiement', models.CharField(choices=[('virement', 'Virement'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='virement', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frais', models.ManyToManyField(blank=True, related_name='remboursements', to='api.frais')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='api.proprietaire')),
            ],
            options={
                'db_table': 'remboursement',
                'ordering': ['-date_versement'],
            },
        ),
        migrations.CreateModel(
            name='VersementRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField()),
                ('moyen_paiement', models.CharField(choices=[('virement', 'Virement'), ('especes', 'Espèces'), ('cheque', 'Chèque'), ('autre', 'Autre')], default='virement', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_revenu', to='api.bien')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements_revenu', to='api.proprietaire')),
            ],
            options={
                'db_table': 'versement_revenu',
                'ordering': ['-date_versement'],
            },
        ),
    ]
