# Generated by Django 5.2.16 on 2026-07-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apportinitial_remboursement_versementrevenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietaire',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
