# Generated by Django 5.2.16 on 2026-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_proprietaire_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partproprietaire',
            options={'ordering': ['bien']},
        ),
        migrations.RemoveField(
            model_name='bien',
            name='poids_investissement_financier_pct',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='poids_investissement_temporel_pct',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='poids_quote_part_pct',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='valorisation_heure_proprietaire',
        ),
        migrations.RemoveField(
            model_name='partproprietaire',
            name='quote_part_pct',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_paiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
