# Generated by Django 5.2.16 on 2026-07-19 20:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_partproprietaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='valorisation_heure_proprietaire',
            field=models.DecimalField(decimal_places=2, default=api.models._valorisation_heure_defaut, max_digits=8),
        ),
    ]
